ALKSiteBundle_homepage:
    pattern:  /
    defaults: { _controller: ALKSiteBundle:Default:index }


ALKSiteBundle_hello:
    pattern:  /hello/{name}
    defaults: { _controller: ALKSiteBundle:Default:hello }


ALKSiteBundle_voirarticle:
    pattern:  /node/{id}
    defaults: { _controller: ALKSiteBundle:Default:voirarticle }


ALKSiteBundle_ajouterarticle:
    pattern:  /add/node/
    defaults: { _controller: ALKSiteBundle:Default:ajouter }

ALKSiteBundle_modifierArticle:
    pattern:  /edit/node/{id}
    defaults: { _controller: ALKSiteBundle:Default:modifierArticle }


ALKSiteBundle_voirlesArticles:
    pattern:  /liste/node/{tag}/{page}
    defaults: { _controller: ALKSiteBundle:Default:listeArticles, tag: "Default", page: 1 }
    requirements:
        page: \d*

ALKSiteBundle_voirlesArticles2:
    pattern:  /liste/node/
    defaults: { _controller: ALKSiteBundle:Default:listeArticles, tag: "Default", page: 1 }


