parameters:
#    alk_site.example.class: ALK\Bundle\SiteBundle\Example

services:
#    alk_site.example:
#        class: %alk_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    alk_site.ckeditor:
        class:        ALK\Bundle\SiteBundle\Form\Type\CkeditorType
        tags:
            - { name: form.type, alias: ckeditor }