ALKSiteBundle:
    resource: "@ALKSiteBundle/Resources/config/routing.yml"
    prefix:   /

ALKSiteBundle_crud:
    resource: "@ALKSiteBundle/Resources/config/routing/article.yml"
    prefix:   /crud

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
