ALKSiteBundle:
    resource: "@ALKSiteBundle/Resources/config/routing.yml"
    prefix:   /


acme_hello:
    resource: "@ALKSiteBundle/Resources/config/routing/article.yml"

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
