<?php

namespace ALK\Bundle\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryRepository extends EntityRepository
{
    public function myFindAll($max)
    {
        $queryBuilder = $this->createQueryBuilder('a')->setMaxResults(10);
        $queryBuilder->add('orderBy', 'a.id DESC');

        $query = $queryBuilder->getQuery();

        $resultats = $query->getResult();

        return $resultats;
    }

}